### ISSUE TITLE
Error uploading logs spanning > 24 hours

### ISSUE THREAD

**Issue by lincheney** [lincheney/journald-2-cloudwatch#1]
Uploading a batch of logs spanning > 24 hours fails. This can occur if the server has been down for a few days.
The log uploader will need to be more intelligent and split up the batch appropriately.
### Traceback:

```
Traceback (most recent call last):
File "/main.py", line 181, in <module>
client.log_messages(log_stream, list(messages))
File "/main.py", line 97, in log_messages
self._log_messages(log_stream, messages[i : (i+chunk)])
File "/main.py", line 106, in _log_messages
self.put_log_messages(log_stream, messages)
File "/main.py", line 91, in put_log_messages
**kwargs
File "/usr/local/lib/python3.4/dist-packages/botocore/client.py", line 228, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/usr/local/lib/python3.4/dist-packages/botocore/client.py", line 492, in _make_api_call
raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidParameterException) when calling the PutLogEvents operation: The batch of log events in a single PutLogEvents req
```

**Comment by lincheney** [comment]
Fixed in https://github.com/lincheney/journald-2-cloudwatch/commit/c0d93f75dd51ba45f91b0f5a17000a38455aa44f
