### ISSUE TITLE
HTTP 500 from cloudwatch API causes service to fail 

### ISSUE THREAD

**Issue by brentsnook** [lincheney/journald-2-cloudwatch#3]
Hi Cheney,

We noticed this morning that there seemed to be a few hiccups with the AWS cloudwatch API. This lead to the service being marked as failed.

```
Jul 27 02:19:43 ... systemd[1]: Started journald_wrapper.
Jul 27 23:58:29 ... docker[1079]: Traceback (most recent call last):
Jul 27 23:58:29 ... docker[1079]: File "/main.py", line 195, in <module>
Jul 27 23:58:29 ... docker[1079]: client.log_messages(log_stream, list(messages))
Jul 27 23:58:29 ... docker[1079]: File "/main.py", line 111, in log_messages
Jul 27 23:58:29 ... docker[1079]: self._log_messages(log_stream, chunk)
Jul 27 23:58:29 ... docker[1079]: File "/main.py", line 120, in _log_messages
Jul 27 23:58:29 ... docker[1079]: self.put_log_messages(log_stream, messages)
Jul 27 23:58:29 ... docker[1079]: File "/main.py", line 82, in put_log_messages
Jul 27 23:58:29 ... docker[1079]: seq_token = self.get_seq_token(log_stream)
Jul 27 23:58:29 ... docker[1079]: File "/main.py", line 133, in get_seq_token
Jul 27 23:58:29 ... docker[1079]: streams = self.client.describe_log_streams(logGroupName=self.log_group, logStreamNamePrefix=log_stream, limit=1)
Jul 27 23:58:29 ... docker[1079]: File "/usr/local/lib/python3.4/dist-packages/botocore/client.py", line 262, in _api_call
Jul 27 23:58:29 ... docker[1079]: return self._make_api_call(operation_name, kwargs)
Jul 27 23:58:29 ... docker[1079]: File "/usr/local/lib/python3.4/dist-packages/botocore/client.py", line 552, in _make_api_call
Jul 27 23:58:29 ... docker[1079]: raise ClientError(parsed_response, operation_name)
Jul 27 23:58:29 ... docker[1079]: botocore.exceptions.ClientError: An error occurred (500) when calling the DescribeLogStreams operation: Internal Server Error
Jul 27 23:58:29 ... systemd[1]: journald_wrapper.service: Main process exited, code=exited, status=1/FAILURE
Jul 27 23:58:29 ... docker[2461]: journald_wrapper
Jul 27 23:58:29 ... docker[2467]: journald_wrapper
Jul 27 23:58:29 ... systemd[1]: journald_wrapper.service: Unit entered failed state.
Jul 27 23:58:29 ... systemd[1]: journald_wrapper.service: Failed with result 'exit-code'.
```

Would it be better to handle a 500 or other HTTP errors and just log the failure somewhere so the service is tolerant to AWS problems?

**Comment by lincheney** [comment]
@brentsnook 
I'll have to see what the "official" cloudwatch logs agent does on meeting these errors.
Otherwise the workaround for now is simply for you stick a restart into your unit file.
